# Generated by Django 3.2.8 on 2021-11-01 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Article Type Name')),
                ('color', models.CharField(max_length=80, verbose_name='Article Type Color')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Article Name')),
                ('short_description', models.CharField(max_length=80, verbose_name='Article Short Description')),
                ('long_description', models.CharField(max_length=254, verbose_name='Article Long Description')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news.articletype', verbose_name='Article Type')),
            ],
        ),
    ]
